---
title: "ABC Data - Segregation Figures"
output: html_notebook
---

```{r}
library(ggplot2)
library(dplyr)
```

### Clear Workspace
```{r}
rm(list = ls())
```

### Set working directory
```{r}
setwd("/Users/astridrr/Desktop/Wiers_Lab/ABC_FC/Astrid_code")
```

### Load Segretation data

```{r}
data_alc <- read_excel("alc_dem_cognorm.xlsx") # Imports the Alcohol Use data
data_seg <- read_excel("seg_dem_cognorm.xlsx")[,-(2:4)] # Imports the Segregation data excluding columns 2 to 4

data <- merge(data_alc, data_seg, by ="Sub ID") # Merges Alcohol and Segregation data by Subject ID
```

### Prepare Data and variables

```{r}
ntws <- names(data_seg)[(2:19)]
data$Sex <- recode(data$Sex, 'Female'=0,'Male'=1)
data$ALCOHOL <- recode(data$ALCOHOL,'2'=1)
data$ALCFREQ[is.na(data$ALCFREQ)] <- 0
data$ALCFREQ %<>% factor()
```

#### Clears the console
```{r}
cat("\f")
```

```{r}
# Loop through each variable in ntws and create scatter plots
for (var in ntws) {
  plot_data <- data.frame(Age = data$Age, Segregation = data[[var]])
  
  fig <- ggplot(plot_data, aes(x = Age, y = Segregation)) +
    geom_point() +
    geom_smooth(method = "lm", formula = y ~ 1 + x, se = FALSE, color = "blue") +  # Add regression line
    labs(x = "Age", y = "Segregation") +  # Set x and y axis labels
    ggtitle(paste("Scatter plot of", var, "vs. Age"))  # Set plot title
  
  # Print the plot to the console
  print(fig)
}
```


```{r}
subs <- c(7, 44, 67, 73, 88, 144, 233, 156, 123, 141, 133, 93, 222, 135)
lmdata <- filter_all(data, any_vars(data$`Sub ID` %in% subs))

# Loop through each variable in ntws and create scatter plots with regression lines
for (var in ntws) {
    plot_data <- data.frame(Age = lmdata$Age, Segregation = lmdata[[var]])
    # Defines the linear model for the current network
    mdl <- as.formula(paste0("`", var, "`", " ~ 1 + AgeatMRI * ALCOHOL"))
    # Fits the linear model for the current network to the data
    lm_model <- lm(mdl, data = lmdata)
    # Add predicted values to the original dataset
    predicted <- predict(object = lm_model, newdata = lmdata)
    
    plot_data <- transform(plot_data, Predicted = predicted)
    
    fig <- ggplot(plot_data, aes(x = Age, y = Segregation, col = factor(lmdata$ALCOHOL))) +
        geom_point() +
        geom_line(aes(y = Predicted, group = factor(lmdata$ALCOHOL), col = factor(lmdata$ALCOHOL))) +  # Add predicted lines for each ALCOHOL group with respective colors
        labs(x = "Age", y = "Segregation", colour = "ALCOHOL") +  # Set x and y axis labels
        ggtitle(paste("Scatter plot of", var, "vs. Age"))  # Set plot title
    
    print(fig)
}

```

```{r}
subs <- c(44, 45, 58, 93, 104, 107, 117, 123, 130, 133, 135, 136, 138, 139, 141, 
          142, 144, 145, 146, 148, 153, 155, 156, 166, 168, 169, 174, 176, 178, 
          179, 180, 182, 183, 184, 186, 187, 188, 190, 191, 192, 193, 194, 195,
          198, 199, 207, 210, 212, 215, 218, 219, 220, 221, 222, 223, 224, 229,
          230, 232, 233, 239, 241, 251, 252)

lmdata <- filter_all(data, any_vars(data$`Sub ID` %in% subs))

# Loop through each variable in ntws and create box plots with individual data points for each ALCFREQ group
for (var in ntws) {
    fig <- ggplot(lmdata, aes(x = factor(ALCFREQ), y = lmdata[[var]], col = factor(ALCFREQ))) +
        geom_boxplot(alpha = 0.6) +  # Create box plots for each ALCFREQ group
        geom_jitter(position = position_jitter(width = 0.3), alpha = 0.4, size = 2) +  # Add jittered points
        labs(x = "ALCFREQ", y = var) +  # Set x and y axis labels
        ggtitle(paste("Box plot of", var, "by ALCFREQ")) +  # Set plot title
        scale_x_discrete(labels = c("less than 1 a month", "around 1 a month", "around 1 a week", "a few a week",
                                    "daily or almost daily")) +
        guides(color = FALSE)  # Remove the legend for color
    
    print(fig)
}

```

